"""empty message

Revision ID: 4958e9a5085a
Revises: 9a7bc43c6197
Create Date: 2021-03-09 16:54:47.536439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4958e9a5085a'
down_revision = '9a7bc43c6197'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=120), nullable=False),
    sa.Column('Lastname', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('Cedula', sa.String(length=120), nullable=False),
    sa.Column('Edad', sa.String(length=120), nullable=True),
    sa.Column('Fecha_Nacimiento', sa.String(length=120), nullable=True),
    sa.Column('Telefono_Usuario', sa.String(length=120), nullable=True),
    sa.Column('Nombre_Cuidador', sa.String(length=120), nullable=True),
    sa.Column('Telefono_Cuidador', sa.String(length=120), nullable=True),
    sa.Column('Peso_Usuario', sa.String(length=120), nullable=True),
    sa.Column('Altura_Usuario', sa.String(length=120), nullable=True),
    sa.Column('Profecion', sa.String(length=120), nullable=True),
    sa.Column('Medicamentos_Actuales', sa.String(length=240), nullable=True),
    sa.Column('Enfermedades', sa.String(length=120), nullable=True),
    sa.Column('Alergias_Medicamentosas_Alimenticias', sa.String(length=240), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Cedula'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_info')
    # ### end Alembic commands ###
