"""empty message

Revision ID: 61f4665dd828
Revises: b13477303960
Create Date: 2021-03-10 23:34:12.396108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61f4665dd828'
down_revision = 'b13477303960'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medicamentos', 'marcas_comerciales')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicamentos', sa.Column('marcas_comerciales', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
