"""empty message

Revision ID: a885ffcea85a
Revises: 4958e9a5085a
Create Date: 2021-03-09 17:00:18.305016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a885ffcea85a'
down_revision = '4958e9a5085a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('Profesion', sa.String(length=120), nullable=False))
    op.alter_column('user_info', 'Alergias_Medicamentosas_Alimenticias',
               existing_type=sa.VARCHAR(length=240),
               nullable=False)
    op.alter_column('user_info', 'Altura_Usuario',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user_info', 'Enfermedades',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user_info', 'Fecha_Nacimiento',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user_info', 'Medicamentos_Actuales',
               existing_type=sa.VARCHAR(length=240),
               nullable=False)
    op.alter_column('user_info', 'Nombre_Cuidador',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user_info', 'Peso_Usuario',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user_info', 'Telefono_Cuidador',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user_info', 'Telefono_Usuario',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_column('user_info', 'Profecion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('Profecion', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.alter_column('user_info', 'Telefono_Usuario',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user_info', 'Telefono_Cuidador',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user_info', 'Peso_Usuario',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user_info', 'Nombre_Cuidador',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user_info', 'Medicamentos_Actuales',
               existing_type=sa.VARCHAR(length=240),
               nullable=True)
    op.alter_column('user_info', 'Fecha_Nacimiento',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user_info', 'Enfermedades',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user_info', 'Altura_Usuario',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user_info', 'Alergias_Medicamentosas_Alimenticias',
               existing_type=sa.VARCHAR(length=240),
               nullable=True)
    op.drop_column('user_info', 'Profesion')
    # ### end Alembic commands ###
